/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b09a9b53-dd23-4784-9faf-5203afa66298",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_0ZhflBCPA",
    "aws_user_pools_web_client_id": "67efjihmjvk7efh0ohg3ikm69n",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://lydfpkhhdzcz7oiwk4zyzwd6f4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
